//! Order type definitions for Flash.
//!
//! This module defines the core order types used throughout the order management
//! system. All types are designed for:
//!
//! - **Zero-Copy Serialization**: Efficient bincode encoding for BlackBox
//! - **Serde Compatible**: JSON serialization for debugging/logging
//! - **Thread-Safe**: All types are `Send + Sync`
//!
//! # Types Overview
//!
//! | Type | Description | Size |
//! |------|-------------|------|
//! | `OrderId` | Unique order identifier | 8 bytes |
//! | `OrderType` | Market/Limit/StopLimit | 1 byte |
//! | `OrderSide` | Buy/Sell | 1 byte |
//! | `TimeInForce` | GTC/IOC/FOK | 1 byte |
//! | `OrderRequest` | Full order submission | ~128 bytes |

use crate::core::types::{Instrument, Quantity, Timestamp};
use serde::{Deserialize, Serialize};
use std::fmt;

// =============================================================================
// ORDER ID
// =============================================================================

/// Unique order identifier.
///
/// A 64-bit unsigned integer that uniquely identifies an order within the system.
/// Order IDs are generated by the [`OrderManager`] and are monotonically increasing.
///
/// # Example
///
/// ```
/// use astra_flash::order::OrderId;
///
/// let id = OrderId::new(12345);
/// assert_eq!(id.as_u64(), 12345);
/// assert_eq!(id.to_string(), "12345");
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OrderId(u64);

impl OrderId {
    /// Creates a new order ID from a u64 value.
    #[must_use]
    pub const fn new(id: u64) -> Self {
        Self(id)
    }

    /// Returns the underlying u64 value.
    #[must_use]
    pub const fn as_u64(&self) -> u64 {
        self.0
    }
}

impl fmt::Display for OrderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<u64> for OrderId {
    fn from(value: u64) -> Self {
        Self::new(value)
    }
}

// =============================================================================
// ORDER SIDE
// =============================================================================

/// Order side (buy or sell).
///
/// Distinct from [`Side`](crate::core::types::Side) which represents book side.
/// This enum represents the trading intent.
///
/// # Example
///
/// ```
/// use astra_flash::order::OrderSide;
///
/// let side = OrderSide::Buy;
/// assert_eq!(side.as_str(), "buy");
/// assert_eq!(side.opposite(), OrderSide::Sell);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderSide {
    /// Buy order (bid).
    Buy,
    /// Sell order (ask).
    Sell,
}

impl OrderSide {
    /// Returns the opposite side.
    #[must_use]
    pub const fn opposite(&self) -> Self {
        match self {
            Self::Buy => Self::Sell,
            Self::Sell => Self::Buy,
        }
    }

    /// Returns the string representation.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Buy => "buy",
            Self::Sell => "sell",
        }
    }
}

impl fmt::Display for OrderSide {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// =============================================================================
// ORDER TYPE
// =============================================================================

/// Order type classification.
///
/// Defines how the order should be executed by the exchange.
///
/// # Example
///
/// ```
/// use astra_flash::order::OrderType;
///
/// let order_type = OrderType::Limit;
/// assert_eq!(order_type.as_str(), "limit");
/// assert!(order_type.requires_price());  // Limit orders require a price
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderType {
    /// Market order - execute at best available price.
    Market,
    /// Limit order - execute at specified price or better.
    Limit,
    /// Stop limit order - becomes limit order when stop price is reached.
    StopLimit,
    /// Stop market order - becomes market order when stop price is reached.
    StopMarket,
}

impl OrderType {
    /// Returns the string representation.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Market => "market",
            Self::Limit => "limit",
            Self::StopLimit => "stop_limit",
            Self::StopMarket => "stop_market",
        }
    }

    /// Returns true if this order type requires a price.
    #[must_use]
    pub const fn requires_price(&self) -> bool {
        match self {
            Self::Market | Self::StopMarket => false,
            Self::Limit | Self::StopLimit => true,
        }
    }

    /// Returns true if this order type requires a stop price.
    #[must_use]
    pub const fn requires_stop_price(&self) -> bool {
        matches!(self, Self::StopLimit | Self::StopMarket)
    }
}

impl fmt::Display for OrderType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// =============================================================================
// TIME IN FORCE
// =============================================================================

/// Time-in-force specification.
///
/// Defines how long an order remains active before being cancelled.
///
/// # Example
///
/// ```
/// use astra_flash::order::TimeInForce;
///
/// let tif = TimeInForce::GTC;
/// assert_eq!(tif.as_str(), "GTC");
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub enum TimeInForce {
    /// Good-Till-Cancelled - remains active until filled or cancelled.
    #[default]
    GTC,
    /// Immediate-Or-Cancel - fill what can be filled, cancel the rest.
    IOC,
    /// Fill-Or-Kill - fill completely or cancel entirely.
    FOK,
    /// Good-Till-Date - expires at specified time.
    GTD,
    /// Post-Only - only add liquidity, never take.
    PostOnly,
}

impl TimeInForce {
    /// Returns the string representation.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::GTC => "GTC",
            Self::IOC => "IOC",
            Self::FOK => "FOK",
            Self::GTD => "GTD",
            Self::PostOnly => "POST_ONLY",
        }
    }
}

impl fmt::Display for TimeInForce {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// =============================================================================
// ORDER STATUS
// =============================================================================

/// Order lifecycle status.
///
/// Tracks the current state of an order from submission to completion.
///
/// # State Machine
///
/// ```text
/// Pending ──submit──> Submitted ──ack──> Open ──fill──> Filled
///                          │                │               │
///                          │              cancel           partial
///                          │                │               │
///                          └──reject──> Rejected      PartiallyFilled
///                                                           │
///                                                       cancel
///                                                           │
///                                                       Cancelled
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderStatus {
    /// Order created but not yet sent to exchange.
    Pending,
    /// Order sent to exchange, awaiting acknowledgment.
    Submitted,
    /// Order acknowledged by exchange and active.
    Open,
    /// Order partially filled.
    PartiallyFilled,
    /// Order completely filled.
    Filled,
    /// Order cancelled (by user or system).
    Cancelled,
    /// Order rejected by exchange.
    Rejected,
    /// Order expired (GTD orders).
    Expired,
}

impl OrderStatus {
    /// Returns the string representation.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Submitted => "submitted",
            Self::Open => "open",
            Self::PartiallyFilled => "partially_filled",
            Self::Filled => "filled",
            Self::Cancelled => "cancelled",
            Self::Rejected => "rejected",
            Self::Expired => "expired",
        }
    }

    /// Returns true if the order is in a terminal state.
    #[must_use]
    pub const fn is_terminal(&self) -> bool {
        matches!(
            self,
            Self::Filled | Self::Cancelled | Self::Rejected | Self::Expired
        )
    }

    /// Returns true if the order can be cancelled.
    #[must_use]
    pub const fn is_cancellable(&self) -> bool {
        matches!(self, Self::Open | Self::PartiallyFilled | Self::Submitted)
    }
}

impl fmt::Display for OrderStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// =============================================================================
// ORDER REQUEST
// =============================================================================

/// Order submission request.
///
/// Contains all information needed to submit an order to an exchange.
/// This struct is serialized and recorded to the BlackBox journal when
/// the `blackbox` feature is enabled.
///
/// # Example
///
/// ```
/// use astra_flash::order::{OrderRequest, OrderType, OrderSide, TimeInForce};
/// use astra_flash::core::types::{Exchange, Instrument, now_micros};
/// use rust_decimal_macros::dec;
///
/// let instrument = Instrument::new("BTC", "USD", Exchange::Deribit, "BTC-PERPETUAL");
/// let order = OrderRequest::limit(
///     instrument,
///     OrderSide::Buy,
///     50000.0,
///     dec!(1.0),
///     TimeInForce::GTC,
///     now_micros(),
/// );
///
/// assert_eq!(order.order_type, OrderType::Limit);
/// assert_eq!(order.side, OrderSide::Buy);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderRequest {
    /// Instrument to trade.
    pub instrument: Instrument,

    /// Order side (buy/sell).
    pub side: OrderSide,

    /// Order type (market/limit/stop).
    pub order_type: OrderType,

    /// Order quantity.
    pub quantity: Quantity,

    /// Limit price (required for Limit and StopLimit orders).
    /// Stored as f64 for serialization compatibility.
    pub price: Option<f64>,

    /// Stop trigger price (required for Stop orders).
    /// Stored as f64 for serialization compatibility.
    pub stop_price: Option<f64>,

    /// Time in force.
    pub time_in_force: TimeInForce,

    /// Client-defined order ID (optional).
    pub client_order_id: Option<String>,

    /// Reduce-only flag (close positions only).
    pub reduce_only: bool,

    /// Post-only flag (add liquidity only).
    pub post_only: bool,

    /// Creation timestamp (microseconds).
    pub created_at: Timestamp,
}

impl OrderRequest {
    /// Creates a new market order request.
    ///
    /// Market orders execute immediately at the best available price.
    ///
    /// # Arguments
    ///
    /// * `instrument` - Trading instrument
    /// * `side` - Buy or sell
    /// * `quantity` - Order quantity
    /// * `timestamp` - Creation timestamp
    ///
    /// # Example
    ///
    /// ```
    /// use astra_flash::order::{OrderRequest, OrderSide};
    /// use astra_flash::core::types::{Exchange, Instrument, now_micros};
    /// use rust_decimal_macros::dec;
    ///
    /// let instrument = Instrument::new("BTC", "USD", Exchange::Deribit, "BTC-PERPETUAL");
    /// let order = OrderRequest::market(instrument, OrderSide::Buy, dec!(1.0), now_micros());
    /// ```
    #[must_use]
    pub const fn market(
        instrument: Instrument,
        side: OrderSide,
        quantity: Quantity,
        timestamp: Timestamp,
    ) -> Self {
        Self {
            instrument,
            side,
            order_type: OrderType::Market,
            quantity,
            price: None,
            stop_price: None,
            time_in_force: TimeInForce::IOC,
            client_order_id: None,
            reduce_only: false,
            post_only: false,
            created_at: timestamp,
        }
    }

    /// Creates a new limit order request.
    ///
    /// Limit orders execute at the specified price or better.
    ///
    /// # Arguments
    ///
    /// * `instrument` - Trading instrument
    /// * `side` - Buy or sell
    /// * `price` - Limit price
    /// * `quantity` - Order quantity
    /// * `time_in_force` - How long the order remains active
    /// * `timestamp` - Creation timestamp
    ///
    /// # Example
    ///
    /// ```
    /// use astra_flash::order::{OrderRequest, OrderSide, TimeInForce};
    /// use astra_flash::core::types::{Exchange, Instrument, now_micros};
    /// use rust_decimal_macros::dec;
    ///
    /// let instrument = Instrument::new("BTC", "USD", Exchange::Deribit, "BTC-PERPETUAL");
    /// let order = OrderRequest::limit(
    ///     instrument,
    ///     OrderSide::Buy,
    ///     50000.0,
    ///     dec!(1.0),
    ///     TimeInForce::GTC,
    ///     now_micros(),
    /// );
    /// ```
    #[must_use]
    pub const fn limit(
        instrument: Instrument,
        side: OrderSide,
        price: f64,
        quantity: Quantity,
        time_in_force: TimeInForce,
        timestamp: Timestamp,
    ) -> Self {
        Self {
            instrument,
            side,
            order_type: OrderType::Limit,
            quantity,
            price: Some(price),
            stop_price: None,
            time_in_force,
            client_order_id: None,
            reduce_only: false,
            post_only: false,
            created_at: timestamp,
        }
    }

    /// Creates a new stop-limit order request.
    ///
    /// Stop-limit orders become limit orders when the stop price is reached.
    ///
    /// # Arguments
    ///
    /// * `instrument` - Trading instrument
    /// * `side` - Buy or sell
    /// * `stop_price` - Trigger price
    /// * `limit_price` - Limit price after trigger
    /// * `quantity` - Order quantity
    /// * `timestamp` - Creation timestamp
    #[must_use]
    pub const fn stop_limit(
        instrument: Instrument,
        side: OrderSide,
        stop_price: f64,
        limit_price: f64,
        quantity: Quantity,
        timestamp: Timestamp,
    ) -> Self {
        Self {
            instrument,
            side,
            order_type: OrderType::StopLimit,
            quantity,
            price: Some(limit_price),
            stop_price: Some(stop_price),
            time_in_force: TimeInForce::GTC,
            client_order_id: None,
            reduce_only: false,
            post_only: false,
            created_at: timestamp,
        }
    }

    /// Sets the client order ID.
    #[must_use]
    pub fn with_client_id(mut self, client_id: impl Into<String>) -> Self {
        self.client_order_id = Some(client_id.into());
        self
    }

    /// Sets the reduce-only flag.
    #[must_use]
    pub const fn reduce_only(mut self) -> Self {
        self.reduce_only = true;
        self
    }

    /// Sets the post-only flag.
    #[must_use]
    pub const fn post_only(mut self) -> Self {
        self.post_only = true;
        self
    }
}

// =============================================================================
// CANCEL REASON
// =============================================================================

/// Reason for order cancellation.
///
/// Provides context for why an order was cancelled.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CancelReason {
    /// User requested cancellation.
    UserRequested,
    /// Order expired (GTD).
    Expired,
    /// Insufficient funds/margin.
    InsufficientFunds,
    /// Post-only order would take liquidity.
    PostOnlyWouldTake,
    /// Reduce-only order would increase position.
    ReduceOnlyWouldIncrease,
    /// Self-trade prevention triggered.
    SelfTradePrevention,
    /// Order cancelled due to disconnect.
    Disconnect,
    /// System shutdown/maintenance.
    SystemShutdown,
    /// Risk limit exceeded.
    RiskLimit,
    /// Custom reason with message.
    Other(String),
}

impl CancelReason {
    /// Returns the string representation.
    pub fn as_str(&self) -> &str {
        match self {
            Self::UserRequested => "user_requested",
            Self::Expired => "expired",
            Self::InsufficientFunds => "insufficient_funds",
            Self::PostOnlyWouldTake => "post_only_would_take",
            Self::ReduceOnlyWouldIncrease => "reduce_only_would_increase",
            Self::SelfTradePrevention => "self_trade_prevention",
            Self::Disconnect => "disconnect",
            Self::SystemShutdown => "system_shutdown",
            Self::RiskLimit => "risk_limit",
            Self::Other(msg) => msg,
        }
    }
}

impl fmt::Display for CancelReason {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// =============================================================================
// MODIFY REQUEST
// =============================================================================

/// Order modification request.
///
/// Contains the changes to apply to an existing order.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModifyRequest {
    /// New price (if changing).
    /// Stored as f64 for serialization compatibility.
    pub new_price: Option<f64>,

    /// New quantity (if changing).
    pub new_quantity: Option<Quantity>,

    /// Timestamp of modification request.
    pub timestamp: Timestamp,
}

impl ModifyRequest {
    /// Creates a new modification request to change the price.
    #[must_use]
    pub const fn price(new_price: f64, timestamp: Timestamp) -> Self {
        Self {
            new_price: Some(new_price),
            new_quantity: None,
            timestamp,
        }
    }

    /// Creates a new modification request to change the quantity.
    #[must_use]
    pub const fn quantity(new_quantity: Quantity, timestamp: Timestamp) -> Self {
        Self {
            new_price: None,
            new_quantity: Some(new_quantity),
            timestamp,
        }
    }

    /// Creates a new modification request to change both price and quantity.
    #[must_use]
    pub const fn price_and_quantity(
        new_price: f64,
        new_quantity: Quantity,
        timestamp: Timestamp,
    ) -> Self {
        Self {
            new_price: Some(new_price),
            new_quantity: Some(new_quantity),
            timestamp,
        }
    }
}

// =============================================================================
// TESTS
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::types::{now_micros, Exchange, Instrument};
    use rust_decimal_macros::dec;

    fn test_instrument() -> Instrument {
        Instrument::new("BTC", "USD", Exchange::Deribit, "BTC-PERPETUAL")
    }

    // =========================================================================
    // OrderId Tests
    // =========================================================================

    #[test]
    fn test_order_id_new() {
        let id = OrderId::new(12345);
        assert_eq!(id.as_u64(), 12345);
    }

    #[test]
    fn test_order_id_display() {
        let id = OrderId::new(99999);
        assert_eq!(id.to_string(), "99999");
    }

    #[test]
    fn test_order_id_from_u64() {
        let id: OrderId = 42u64.into();
        assert_eq!(id.as_u64(), 42);
    }

    #[test]
    fn test_order_id_equality() {
        let id1 = OrderId::new(100);
        let id2 = OrderId::new(100);
        let id3 = OrderId::new(200);
        assert_eq!(id1, id2);
        assert_ne!(id1, id3);
    }

    // =========================================================================
    // OrderSide Tests
    // =========================================================================

    #[test]
    fn test_order_side_opposite() {
        assert_eq!(OrderSide::Buy.opposite(), OrderSide::Sell);
        assert_eq!(OrderSide::Sell.opposite(), OrderSide::Buy);
    }

    #[test]
    fn test_order_side_as_str() {
        assert_eq!(OrderSide::Buy.as_str(), "buy");
        assert_eq!(OrderSide::Sell.as_str(), "sell");
    }

    #[test]
    fn test_order_side_display() {
        assert_eq!(OrderSide::Buy.to_string(), "buy");
        assert_eq!(OrderSide::Sell.to_string(), "sell");
    }

    // =========================================================================
    // OrderType Tests
    // =========================================================================

    #[test]
    fn test_order_type_as_str() {
        assert_eq!(OrderType::Market.as_str(), "market");
        assert_eq!(OrderType::Limit.as_str(), "limit");
        assert_eq!(OrderType::StopLimit.as_str(), "stop_limit");
        assert_eq!(OrderType::StopMarket.as_str(), "stop_market");
    }

    #[test]
    fn test_order_type_requires_price() {
        assert!(!OrderType::Market.requires_price());
        assert!(OrderType::Limit.requires_price());
        assert!(OrderType::StopLimit.requires_price());
        assert!(!OrderType::StopMarket.requires_price());
    }

    #[test]
    fn test_order_type_requires_stop_price() {
        assert!(!OrderType::Market.requires_stop_price());
        assert!(!OrderType::Limit.requires_stop_price());
        assert!(OrderType::StopLimit.requires_stop_price());
        assert!(OrderType::StopMarket.requires_stop_price());
    }

    // =========================================================================
    // TimeInForce Tests
    // =========================================================================

    #[test]
    fn test_time_in_force_as_str() {
        assert_eq!(TimeInForce::GTC.as_str(), "GTC");
        assert_eq!(TimeInForce::IOC.as_str(), "IOC");
        assert_eq!(TimeInForce::FOK.as_str(), "FOK");
        assert_eq!(TimeInForce::GTD.as_str(), "GTD");
        assert_eq!(TimeInForce::PostOnly.as_str(), "POST_ONLY");
    }

    #[test]
    fn test_time_in_force_default() {
        assert_eq!(TimeInForce::default(), TimeInForce::GTC);
    }

    // =========================================================================
    // OrderStatus Tests
    // =========================================================================

    #[test]
    fn test_order_status_terminal() {
        assert!(!OrderStatus::Pending.is_terminal());
        assert!(!OrderStatus::Submitted.is_terminal());
        assert!(!OrderStatus::Open.is_terminal());
        assert!(!OrderStatus::PartiallyFilled.is_terminal());
        assert!(OrderStatus::Filled.is_terminal());
        assert!(OrderStatus::Cancelled.is_terminal());
        assert!(OrderStatus::Rejected.is_terminal());
        assert!(OrderStatus::Expired.is_terminal());
    }

    #[test]
    fn test_order_status_cancellable() {
        assert!(!OrderStatus::Pending.is_cancellable());
        assert!(OrderStatus::Submitted.is_cancellable());
        assert!(OrderStatus::Open.is_cancellable());
        assert!(OrderStatus::PartiallyFilled.is_cancellable());
        assert!(!OrderStatus::Filled.is_cancellable());
        assert!(!OrderStatus::Cancelled.is_cancellable());
    }

    // =========================================================================
    // OrderRequest Tests
    // =========================================================================

    #[test]
    fn test_order_request_market() {
        let ts = now_micros();
        let order = OrderRequest::market(test_instrument(), OrderSide::Buy, dec!(1.5), ts);

        assert_eq!(order.order_type, OrderType::Market);
        assert_eq!(order.side, OrderSide::Buy);
        assert_eq!(order.quantity, dec!(1.5));
        assert!(order.price.is_none());
        assert_eq!(order.time_in_force, TimeInForce::IOC);
        assert_eq!(order.created_at, ts);
    }

    #[test]
    fn test_order_request_limit() {
        let ts = now_micros();
        let order = OrderRequest::limit(
            test_instrument(),
            OrderSide::Sell,
            50000.0,
            dec!(2.0),
            TimeInForce::GTC,
            ts,
        );

        assert_eq!(order.order_type, OrderType::Limit);
        assert_eq!(order.side, OrderSide::Sell);
        assert!(order.price.is_some());
        assert_eq!(order.price.unwrap(), 50000.0);
        assert_eq!(order.quantity, dec!(2.0));
        assert_eq!(order.time_in_force, TimeInForce::GTC);
    }

    #[test]
    fn test_order_request_stop_limit() {
        let ts = now_micros();
        let order = OrderRequest::stop_limit(
            test_instrument(),
            OrderSide::Buy,
            48000.0, // stop
            48100.0, // limit
            dec!(0.5),
            ts,
        );

        assert_eq!(order.order_type, OrderType::StopLimit);
        assert!(order.stop_price.is_some());
        assert_eq!(order.stop_price.unwrap(), 48000.0);
        assert!(order.price.is_some());
        assert_eq!(order.price.unwrap(), 48100.0);
    }

    #[test]
    fn test_order_request_with_client_id() {
        let ts = now_micros();
        let order = OrderRequest::market(test_instrument(), OrderSide::Buy, dec!(1.0), ts)
            .with_client_id("my-order-123");

        assert_eq!(order.client_order_id, Some("my-order-123".to_string()));
    }

    #[test]
    fn test_order_request_reduce_only() {
        let ts = now_micros();
        let order =
            OrderRequest::market(test_instrument(), OrderSide::Sell, dec!(1.0), ts).reduce_only();

        assert!(order.reduce_only);
    }

    #[test]
    fn test_order_request_post_only() {
        let ts = now_micros();
        let order = OrderRequest::limit(
            test_instrument(),
            OrderSide::Buy,
            50000.0,
            dec!(1.0),
            TimeInForce::GTC,
            ts,
        )
        .post_only();

        assert!(order.post_only);
    }

    // =========================================================================
    // CancelReason Tests
    // =========================================================================

    #[test]
    fn test_cancel_reason_as_str() {
        assert_eq!(CancelReason::UserRequested.as_str(), "user_requested");
        assert_eq!(CancelReason::Expired.as_str(), "expired");
        assert_eq!(
            CancelReason::InsufficientFunds.as_str(),
            "insufficient_funds"
        );
    }

    #[test]
    fn test_cancel_reason_other() {
        let reason = CancelReason::Other("custom reason".to_string());
        assert_eq!(reason.as_str(), "custom reason");
    }

    // =========================================================================
    // ModifyRequest Tests
    // =========================================================================

    #[test]
    fn test_modify_request_price() {
        let ts = now_micros();
        let modify = ModifyRequest::price(51000.0, ts);

        assert!(modify.new_price.is_some());
        assert_eq!(modify.new_price.unwrap(), 51000.0);
        assert!(modify.new_quantity.is_none());
    }

    #[test]
    fn test_modify_request_quantity() {
        let ts = now_micros();
        let modify = ModifyRequest::quantity(dec!(2.5), ts);

        assert!(modify.new_price.is_none());
        assert!(modify.new_quantity.is_some());
        assert_eq!(modify.new_quantity.unwrap(), dec!(2.5));
    }

    #[test]
    fn test_modify_request_price_and_quantity() {
        let ts = now_micros();
        let modify = ModifyRequest::price_and_quantity(52000.0, dec!(3.0), ts);

        assert!(modify.new_price.is_some());
        assert!(modify.new_quantity.is_some());
    }

    // =========================================================================
    // Serialization Tests
    // =========================================================================

    #[test]
    fn test_order_request_bincode_serialization() {
        // Note: bincode may have issues with deserialize_any, but serialization should work
        let ts = now_micros();
        let order = OrderRequest::limit(
            test_instrument(),
            OrderSide::Buy,
            50000.0,
            dec!(1.0),
            TimeInForce::GTC,
            ts,
        );

        // Test that serialization succeeds (important for TAP-3 recording)
        let bytes = bincode::serialize(&order).expect("Serialization should succeed");

        // Verify the bytes are non-empty and reasonable size
        assert!(!bytes.is_empty(), "Serialized bytes should not be empty");
        assert!(
            bytes.len() < 500,
            "Serialized order should be reasonably sized"
        );
    }

    #[test]
    fn test_order_request_json_roundtrip() {
        let ts = now_micros();
        let order = OrderRequest::market(test_instrument(), OrderSide::Sell, dec!(0.5), ts);

        let json = serde_json::to_string(&order).unwrap();
        let decoded: OrderRequest = serde_json::from_str(&json).unwrap();

        assert_eq!(decoded.side, order.side);
        assert_eq!(decoded.order_type, order.order_type);
    }
}
