//! Build script for blackbox.
//!
//! This script:
//! 1. Embeds the SBE schema XML as a compile-time constant
//! 2. Generates schema hash for verification
//! 3. (Future) Generates Rust code from SBE schema

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../../schemas/blackbox-v1.0.xml");
    println!("cargo:rerun-if-changed=build.rs");

    // Read the schema file
    let schema_path = Path::new("../../schemas/blackbox-v1.0.xml");

    let schema_xml = if schema_path.exists() {
        fs::read_to_string(schema_path).expect("Failed to read schema file")
    } else {
        // Fallback for when building from different directory
        let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
        let alt_path = Path::new(&manifest_dir)
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .join("schemas")
            .join("blackbox-v1.0.xml");

        if alt_path.exists() {
            fs::read_to_string(&alt_path).expect("Failed to read schema file")
        } else {
            // Use embedded fallback for initial build
            eprintln!("Warning: Schema file not found, using empty placeholder");
            String::new()
        }
    };

    // Compute CRC32 of the schema
    let schema_hash = crc32_hash(schema_xml.as_bytes());

    // Generate the constants file
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("schema_constants.rs");

    let schema_escaped = schema_xml
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r");

    let contents = format!(
        r#"// Auto-generated schema constants.
// DO NOT EDIT - generated by build.rs

/// The embedded SBE schema XML.
pub const SCHEMA_XML: &str = "{}";

/// CRC32 hash of the schema for verification.
pub const SCHEMA_HASH: u32 = 0x{:08X};

/// Schema major version (breaking changes).
pub const SCHEMA_VERSION_MAJOR: u8 = 1;
/// Schema minor version (append-only changes).
pub const SCHEMA_VERSION_MINOR: u8 = 0;
"#,
        schema_escaped, schema_hash
    );

    fs::write(&dest_path, contents).expect("Failed to write schema constants");

    println!("cargo:rustc-env=SCHEMA_HASH={:08X}", schema_hash);
}

/// Simple CRC32 implementation for build script.
fn crc32_hash(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFFFFFF;

    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            if crc & 1 != 0 {
                crc = (crc >> 1) ^ 0xEDB88320;
            } else {
                crc >>= 1;
            }
        }
    }

    !crc
}
